### ISSUE TITLE
Support updating copyrights

### ISSUE THREAD

**Issue by chasinglogic** [chasinglogic/licensure#3]

**Comment by chasinglogic** [comment]
i.e. if I have a bunch of 2017 copyright headers I want to go to 2018 should be easy to do

**Comment by marques-work** [comment]
@chasinglogic Hi there! One of my teams are using this utility. As 2023 is around the corner, how are you envisioning this to work? Perhaps I can help build this feature if you had some guidance as to how you intended this to work.

For example:

1. Would `licensure` be smart and tell you with an error message that your copyright headers are there, but outdated? Or just blindly fail since the string doesn't match?
2. Would there be a flag to automatically fix all outdated headers?

**Comment by chasinglogic** [comment]
Hey @marques-work,

I'd say that it should be able to update them automatically with a flag to specify the copyright year which defaults to the current year. This would ideally hook into the existing check process which determines if a license header already exists and update it. Similar to how relicensing would work.

I'd be ok with the auto-fixing being opt-in as long as you can set it in the config file.

Hope that answers all your questions! Thanks for using Licensure

**Comment by marques-work** [comment]
@chasinglogic is it necessary to have a flag to specify the year? It looks like there's already a `year` key in the config file when configuring licenses in `licensure.yml`.

That said, a flag might be:

1. redundant
2. unclear as to its usage -- does it override the years for every configured license? and if not, how should we specify to which license it pertains?

Anyhow, I have a PR that I will submit soon that updates the year, but does not include the `--year` flag because of the aforementioned issues.

**Comment by chasinglogic** [comment]
That makes sense to me @marques-work I totally forgot about that!

**Comment by chasinglogic** [comment]
I will review your PR today

**Comment by chasinglogic** [comment]
@marques-work PR is merged and I just published version 0.3.0 👍
